# Disabling sudo moves build to the Container Based Infrastructure on Travis CI.
sudo: false

language: java
jdk: oraclejdk8

script:
  - bash ci/pr.sh

notifications:
  email: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
